require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PrototypesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Prototype. As you add validations to Prototype, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrototypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all prototypes as @prototypes" do
      prototype = Prototype.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:prototypes)).to eq([prototype])
    end
  end

  describe "GET show" do
    it "assigns the requested prototype as @prototype" do
      prototype = Prototype.create! valid_attributes
      get :show, {:id => prototype.to_param}, valid_session
      expect(assigns(:prototype)).to eq(prototype)
    end
  end

  describe "GET new" do
    it "assigns a new prototype as @prototype" do
      get :new, {}, valid_session
      expect(assigns(:prototype)).to be_a_new(Prototype)
    end
  end

  describe "GET edit" do
    it "assigns the requested prototype as @prototype" do
      prototype = Prototype.create! valid_attributes
      get :edit, {:id => prototype.to_param}, valid_session
      expect(assigns(:prototype)).to eq(prototype)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Prototype" do
        expect {
          post :create, {:prototype => valid_attributes}, valid_session
        }.to change(Prototype, :count).by(1)
      end

      it "assigns a newly created prototype as @prototype" do
        post :create, {:prototype => valid_attributes}, valid_session
        expect(assigns(:prototype)).to be_a(Prototype)
        expect(assigns(:prototype)).to be_persisted
      end

      it "redirects to the created prototype" do
        post :create, {:prototype => valid_attributes}, valid_session
        expect(response).to redirect_to(Prototype.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prototype as @prototype" do
        post :create, {:prototype => invalid_attributes}, valid_session
        expect(assigns(:prototype)).to be_a_new(Prototype)
      end

      it "re-renders the 'new' template" do
        post :create, {:prototype => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested prototype" do
        prototype = Prototype.create! valid_attributes
        put :update, {:id => prototype.to_param, :prototype => new_attributes}, valid_session
        prototype.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested prototype as @prototype" do
        prototype = Prototype.create! valid_attributes
        put :update, {:id => prototype.to_param, :prototype => valid_attributes}, valid_session
        expect(assigns(:prototype)).to eq(prototype)
      end

      it "redirects to the prototype" do
        prototype = Prototype.create! valid_attributes
        put :update, {:id => prototype.to_param, :prototype => valid_attributes}, valid_session
        expect(response).to redirect_to(prototype)
      end
    end

    describe "with invalid params" do
      it "assigns the prototype as @prototype" do
        prototype = Prototype.create! valid_attributes
        put :update, {:id => prototype.to_param, :prototype => invalid_attributes}, valid_session
        expect(assigns(:prototype)).to eq(prototype)
      end

      it "re-renders the 'edit' template" do
        prototype = Prototype.create! valid_attributes
        put :update, {:id => prototype.to_param, :prototype => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prototype" do
      prototype = Prototype.create! valid_attributes
      expect {
        delete :destroy, {:id => prototype.to_param}, valid_session
      }.to change(Prototype, :count).by(-1)
    end

    it "redirects to the prototypes list" do
      prototype = Prototype.create! valid_attributes
      delete :destroy, {:id => prototype.to_param}, valid_session
      expect(response).to redirect_to(prototypes_url)
    end
  end

end
